
eureka:
  instance:
    prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localost:8761/eureka}

okta:
  oauth2:
    issuer: https://dev-44426362.okta.com/oauth2/default
    audience: api://default
